#pragma once

enum biome
{
    OCEAN = 1,
    BEACH,
    SCORCHED,
    BARE,
    TUNDRA,
    SNOW,
    TEMPERATE_DESERT,
    SHRUBLAND,
    TAIGA,
    GRASSLAND,
    TEMPERATE_DECIDUOUS_FOREST,
    TEMPERATE_RAIN_FOREST,
    SUBTROPICAL_DESERT,
    TROPICAL_SEASONAL_FOREST,
    TROPICAL_RAIN_FOREST
};
