#pragma once

enum biome
{
    OCEAN = 1,
    BEACH, // 2
    SCORCHED, // 3
    BARE, // 4
    TUNDRA, // 5
    SNOW, // 6
    TEMPERATE_DESERT, // 7 
    SHRUBLAND, // 8
    TAIGA, // 9
    GRASSLAND, // 10
    TEMPERATE_DECIDUOUS_FOREST, // 11
    TEMPERATE_RAIN_FOREST, // 12
    SUBTROPICAL_DESERT, // 13
    TROPICAL_SEASONAL_FOREST, //14
    TROPICAL_RAIN_FOREST // 15
};
